## NDarray

SyntaxError: invalid syntax (<ipython-input-2-45c3a1ae809e>, line 4)

In [ ]:
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

###Your code here!
import numpy as np

# 1
ary_1 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

# 2
ary_2 = np.array([[1,2,3],
[4,5,6],
[7,8,9],
[10,11,12]])

# 3
ary_3 = np.array([[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [7]:
print(ary_1)
print(ary_2)
print(ary_3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
